# yaml-language-server: $schema=https://cdn.jsdelivr.net/gh/compose-spec/compose-spec@master/schema/compose-spec.json

services:
  develop:
    build: {target: develop}
    environment: {HOME: /tmp}
    volumes: [.:/src:rw, tmp-data:/tmp:rw]
    security_opt: [no-new-privileges:true]

  web:
    build: {target: runtime}
    ports: ['8080:8080/tcp'] # open http://127.0.0.1:8080
    command: serve --show-details --proxy-headers=X-Foo,Bar,Baz_blah --catch-all
    develop: # available since docker compose v2.22, https://docs.docker.com/compose/file-watch/
      watch: [{action: rebuild, path: .}]
    security_opt: [no-new-privileges:true]

  hurl:
    image: ghcr.io/orange-opensource/hurl:4.3.0
    volumes: [.:/src:ro]
    working_dir: /src
    depends_on: {web: {condition: service_healthy}}
    security_opt: [no-new-privileges:true]

volumes:
  tmp-data: {}
